#Ansible Automation Script to start Bastion and Master cs_vmsnapshot
- hosts: localhost
  tasks:
  - name: Power On
    azure_rm_virtualmachineazure_rm_virtualmachine:
      resource_group: redhatocpdemo
      name: ocpcluster-bastion